
name: dependency
on:
  push:
    branches: [ "main" ]

env:
    artifact-name : "my-artifact"

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-artafect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: ${{env.artifact-name}}
            path: .
            
    